global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "yt-archiver-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:8000"]
